// Generate a printable HTML receipt and trigger window.print().
// Avoids external PDF libraries — relies on browser print-to-PDF.

import { formatCurrency, formatDate } from './locale';

export interface ReceiptData {
  receiptNumber: string;
  groupName: string;
  groupCode?: string;
  memberName: string;
  memberEmail: string;
  amount: number;
  date: string;
  paymentMethod?: string;
  reference?: string;
  country?: string;
  treasurer?: string;
}

export function printReceipt(data: ReceiptData): void {
  const html = renderReceiptHtml(data);
  const win = window.open('', '_blank', 'width=600,height=800');
  if (!win) {
    alert('Please allow pop-ups to print the receipt.');
    return;
  }
  win.document.write(html);
  win.document.close();
  setTimeout(() => {
    win.focus();
    win.print();
  }, 250);
}

function renderReceiptHtml(d: ReceiptData): string {
  const amount = formatCurrency(d.amount, d.country);
  const date = formatDate(d.date, d.country);
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>Receipt ${d.receiptNumber}</title>
<style>
  @page { size: A5; margin: 12mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #0f172a; padding: 20px; max-width: 540px; margin: 0 auto; }
  .header { text-align: center; border-bottom: 2px solid #007a38; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { margin: 0; color: #007a38; font-size: 24px; letter-spacing: -0.02em; }
  .subtitle { color: #64748b; font-size: 12px; margin-top: 4px; }
  .receipt-no { background: #f8fafc; padding: 8px 12px; border-radius: 6px; font-family: monospace; font-size: 12px; color: #475569; margin: 16px 0; text-align: center; }
  .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
  .row:last-child { border-bottom: none; }
  .row .label { color: #64748b; }
  .row .value { font-weight: 600; color: #0f172a; }
  .amount-card { background: linear-gradient(135deg, #007a38 0%, #005a28 100%); color: #fff; padding: 24px; border-radius: 12px; text-align: center; margin: 24px 0; }
  .amount-card .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; opacity: 0.85; }
  .amount-card .value { font-size: 32px; font-weight: 700; margin-top: 6px; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 11px; color: #94a3b8; }
  .footer strong { color: #475569; }
  @media print {
    body { padding: 0; }
    .no-print { display: none; }
  }
</style></head>
<body>
  <div class="header">
    <h1>Stokpile</h1>
    <div class="subtitle">Contribution Receipt</div>
  </div>

  <div class="receipt-no">Receipt #${d.receiptNumber}</div>

  <div class="amount-card">
    <div class="label">Amount Received</div>
    <div class="value">${amount}</div>
  </div>

  <div class="row"><span class="label">Group</span><span class="value">${escapeHtml(d.groupName)}</span></div>
  ${d.groupCode ? `<div class="row"><span class="label">Group Code</span><span class="value">${escapeHtml(d.groupCode)}</span></div>` : ''}
  <div class="row"><span class="label">Member</span><span class="value">${escapeHtml(d.memberName)}</span></div>
  <div class="row"><span class="label">Email</span><span class="value">${escapeHtml(d.memberEmail)}</span></div>
  <div class="row"><span class="label">Date</span><span class="value">${date}</span></div>
  ${d.paymentMethod ? `<div class="row"><span class="label">Payment Method</span><span class="value">${escapeHtml(d.paymentMethod)}</span></div>` : ''}
  ${d.reference ? `<div class="row"><span class="label">Reference</span><span class="value">${escapeHtml(d.reference)}</span></div>` : ''}

  <div class="footer">
    This receipt was generated by <strong>Stokpile</strong> on ${new Date().toLocaleString()}.
    ${d.treasurer ? `<br>Issued by ${escapeHtml(d.treasurer)}.` : ''}
    <br>Keep this receipt for your records.
  </div>
</body></html>`;
}

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
